# applications/prd/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/andymartinezot/gitops-argo-cd.git
    targetRevision: HEAD
    path: kustomize/overlays/prd
  destination:
    server: https://kubernetes.default.svc
    namespace: prd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
