# applications/application-set.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/andymartinezot/gitops-argo-cd.git
        revision: HEAD
        directories:
          - path: applications/*
  template:
    metadata:
      name: '{{name}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/andymartinezot/gitops-argo-cd.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'  # This will use the directory name as namespace
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true