# kustomize/overlays/prd/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prd
bases:
  - ../../base
patches:
  - path: replica-count.yaml
  - path: configmap.yaml